<?php
echo $this->inlineScript()->prependFile($this->basePath('js/admin-main'. (APPLICATION_ENV == "development" ? "":".min") . '.js'), 'text/javascript')
    ->prependFile($this->basePath('js/lib'. (APPLICATION_ENV == "development" ? "":".min") . '.js'), 'text/javascript')
    ->prependFile($this->basePath('js/Gettext.js'), 'text/javascript')
    ->prependFile($this->basePath('js/jquery.form.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/dataTables.fixedHeader.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/jquery.datetimepicker.js', 'text/javascript'))
    ->prependFile($this->basePath('js/jquery.dataTables.js', 'text/javascript'))
    ->prependFile($this->basePath('js/jquery.sceditor.xhtml.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/jquery.sceditor.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->prependFile($this->basePath('js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->prependFile($this->basePath('js/jquery-1.11.0.min.js', 'text/javascript'));