<div id="sidebar">
    <ul class="module">
        <?php foreach ($aboutCategories as $category): ?>
            <li>
                <a href="<?php echo $this->url('about_index', array('category' => $category->getUrl())); ?>"<?php echo $this->activeCategory == $category->getUrl() ? ' class="active"' : ""; ?>><?php echo $category->getTitle(); ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<div id="main">
    <div id="aboutCategory">
        <?php
        echo $aboutCategory->getContent();
        ?>
    </div>
</div>