<div class="tableWrapper" data-entity="about">
    <?php echo $this->partial("table_options", array(
        "paginator" => $this->paginator,
        "location" => "about"
    )); ?>
    <div class="tableHeader">
        <div class="tableColumn">
            <span>Id</span>
            <span class="sortable"><?php echo $this->translate("Title"); ?></span>
            <span><?php echo $this->translate("Content"); ?></span>
        </div>
    </div>
    <div class="tableBody">
        <?php
        foreach ($this->paginator as $aboutCategory)
            echo $this->partial('about_category', array(
                "aboutCategory" => $aboutCategory,
            ));
        ?>
    </div>
</div>
