<div class="formWrapper">
    <h2>Add a new Product</h2>
    <?php
    echo $this->showMessages();

    $form->prepare();
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('product');
    $form->setAttribute('action', $this->url('products/add'));
    echo $this->form()->openTag($form);
    //echo $this->formHidden($form->get('security'));
    ?>
    <div class="element">
        <?php
        $productNumber = $fieldset->get('productNumber');
        echo $this->formLabel($productNumber);
        echo $this->formElementErrors($productNumber, array('class' => 'formError'));
        echo $this->formInput($productNumber);
        ?>
    </div>
    <div class="element">
        <?php
        $name = $fieldset->get('name');
        echo $this->formLabel($name);
        echo $this->formElementErrors($name, array('class' => 'formError'));
        echo $this->formInput($name);
        ?>
    </div>
    <div class="element">
        <?php
        $description = $fieldset->get('description');
        echo $this->formLabel($description);
        echo $this->formElementErrors($description, array('class' => 'formError'));
        echo $this->formTextarea($description);
        ?>
    </div>
    <div class="element">
        <?php
        $attributes = $fieldset->get('attributes');
        echo $this->formLabel($attributes);
        echo $this->formElementErrors($attributes, array('class' => 'formError'));
        echo $this->formAttributeSelect($attributes,$encodedAttributes);
        ?>
    </div>
    <div class="element">
        <?php
        $datasheet = $fieldset->get('datasheet');
        echo $this->formLabel($datasheet);
        echo $this->formElementErrors($datasheet, array('class' => 'formError'));
        echo $this->formFile($datasheet);
        ?>
    </div>
    <div class="element">
        <?php
        $thumbnail = $fieldset->get('thumbnail');
        echo $this->formLabel($thumbnail);
        echo $this->formElementErrors($thumbnail, array('class' => 'formError'));
        echo $this->formFile($thumbnail);
        ?>
    </div>
    <div class="element">
        <?php
        $specifications = $fieldset->get('specifications');
        echo $this->formLabel($specifications);
        echo $this->formElementErrors($specifications, array('class' => 'formError'));
        echo $this->formFile($specifications);
        ?>
    </div>
    <div class="element">
        <?php
        $relatedProducts = $fieldset->get('relatedProducts');
        echo $this->formLabel($relatedProducts);
        echo $this->formElementErrors($relatedProducts, array('class' => 'formError'));
        echo $this->formSelect($relatedProducts);
        ?>
    </div>
    <div class="element">
        <?php
        $productVariations = $fieldset->get('productVariations');
        echo $this->formLabel($productVariations);
        echo $this->formElementErrors($productVariations, array('class' => 'formError'));
        echo $this->formSelect($productVariations);
        ?>
    </div>
    <div class="element">
        <?php
        $category = $fieldset->get('category');
        echo $this->formLabel($category);
        echo $this->formElementErrors($category, array('class' => 'formError'));
        echo $this->formSelect($category);
        ?>
    </div>
    <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
    <?php echo $this->form()->closeTag() ?>
</div>