<?php
echo $this->showMessages();

$form->prepare();
/**
 * @var \Zend\Form\Fieldset $fieldset
 */
$fieldset = $form->get('product');
$form->setAttribute('action', $this->url('products/add'));
echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('security'));
?>
<table>
    <thead>
    <tr>
        <th><?php echo $this->translate("Product Number"); ?>*</th>
        <th><?php echo $this->translate("Name"); ?>*</th>
        <th><?php echo $this->translate("Description"); ?>*</th>
        <th><?php echo $this->translate("Attributes"); ?>*</th>
        <th><?php echo $this->translate("Datasheet"); ?></th>
        <th><?php echo $this->translate("Thumbnail"); ?></th>
        <th><?php echo $this->translate("Specifications"); ?></th>
        <th><?php echo $this->translate("Related Products"); ?></th>
        <th><?php echo $this->translate("Product Variations"); ?></th>
        <th><?php echo $this->translate("Category"); ?></th>
        <th><?php echo $this->translate("Add"); ?></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <?php
            echo $this->formElementErrors($fieldset->get('productNumber'), array('class' => 'formError'));
            echo $this->formInput($fieldset->get('productNumber'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formElementErrors($fieldset->get('name'), array('class' => 'formError'));
            echo $this->formInput($fieldset->get('name'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formElementErrors($fieldset->get('description'), array('class' => 'formError'));
            echo $this->formTextarea($fieldset->get('description'));
            ?>
        </td>
        <td>
            <div class="attributeGuide invisible">
                <span class="attributeId invisible exclude">Id</span>
                <span class="name">Name</span>
                <span class="value">Value</span>
                <span class="position">Position</span>
            </div>
            <ul class="attributes invisible dynamicList">
            </ul>
            <span class="editAttributes editButton">Edit</span>
        </td>
        <td>
            <?php
            echo $this->formElementErrors($fieldset->get('datasheet'), array('class' => 'formError'));
            echo $this->formFile($fieldset->get('datasheet'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formElementErrors($fieldset->get('thumbnail'), array('class' => 'formError'));
            echo $this->formFile($fieldset->get('thumbnail'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formElementErrors($fieldset->get('specifications'), array('class' => 'formError'));
            echo $this->formFile($fieldset->get('specifications'));
            ?>
        </td>
        <td>
            <div class="attributeGuide invisible">
                <span class="productNumber">Product Number</span>
                <span class="position">Position</span>
            </div>
            <ul class="relatedProducts invisible dynamicList">
            </ul>
            <span class="editAttributes editButton">Edit</span>
        </td>
        <td>
            <div class="attributeGuide invisible">
                <span class="productNumber">Product Number</span>
                <span class="position">Position</span>
            </div>
            <ul class="productVariations invisible dynamicList">
            </ul>
            <span class="editAttributes editButton">Edit</span>
        </td>
        <td>
            <?php
            echo $this->formSelect($fieldset->get('category'));
            echo $this->formElementErrors($fieldset->get('category'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
        </td>
    </tr>
    </tbody>
</table>
<?php echo $this->form()->closeTag() ?>