<div class="search">
    <input type="text" placeholder="Search for a product.."/>
</div>
<ul id="categories">
    <?php
    /**
     * @var \Product\Entity\Category $category
     */
    foreach ($this->categories as $key => $category) :
        ?>
        <li<?php echo ($key+1)%3 === 0 ? ' class="lastInlineItem"' : ""; ?>>
            <a href="<?php echo $this->url('products_index/category',array("categoryUrl"=>$category->getUrl())); ?>">
                <span class="categoryThumbnail"><img
                        src="<?php echo $this->basePath('images/categories/' . $category->getThumbnail()); ?>" ?></span>
                <span class="categoryName"><?php echo $category->getName(); ?></span>
            </a>
        </li>
    <?php endforeach; ?>
</ul>