<div class="tableWrapper" data-entity="products">
    <?php echo $this->partial("table_options", array(
        "paginator" => $this->paginator,
        "location" => "products"
    )); ?>
    <div class="tableHeader">
        <div class="tableColumn">
            <span>Id</span>
            <span class="sortable"><?php echo $this->translate("Product Number"); ?></span>
            <span class="sortable"><?php echo $this->translate("Name"); ?></span>
            <span><?php echo $this->translate("Description"); ?></span>
            <span><?php echo $this->translate("Attributes"); ?></span>
            <span><?php echo $this->translate("Datasheet"); ?></span>
            <span><?php echo $this->translate("Thumbnail"); ?></span>
            <span><?php echo $this->translate("Specifications"); ?></span>
            <span><?php echo $this->translate("Related Products"); ?></span>
            <span><?php echo $this->translate("Product Variations"); ?></span>
            <span><?php echo $this->translate("Category"); ?></span>
        </div>
    </div>
    <div class="tableBody">
        <?php
        foreach ($this->paginator as $product)
                 echo $this->partial('admin_product', array(
                     "product" => $product,
                     "attributes" => $attributes,
                     "categories" => $categories,
                     "productsAssoc" => $productsAssoc
                 ));
        ?>
    </div>
</div>