<?php
if (!empty($products)):
    /**
     * @var \Product\Entity\Product $product
     */
    foreach ($products as $key => $product): ?>
        <li class="product<?php echo ($key + 1) % 3 === 0 ? ' lastInlineItem' : ""; ?>">
            <a href="<?php echo $this->url('products_index/product_uncategorised', array("productNumber" => $product->getProductNumber())); ?>"
               title="<?php echo $product->getName(); ?>">
                <img
                    src="<?php echo $this->basePath('images/products/' . $product->getThumbnail()); ?>"/>
                <span><?php echo $product->getName(); ?></span>
            </a>
        </li>
    <?php endforeach;
else:?>
<li class="notFound">There were no products found matching your query.</li>
<?php endif;?>