<div class="formWrapper">
    <h2>Add a new Category</h2>
    <?php
    $form->prepare();
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('category');
    $form->setAttribute('action', $this->url('categories/add'));
    echo $this->form()->openTag($form);
    //echo $this->formHidden($form->get('security'));
    ?>
    <div class="element">
        <?php
        $name = $fieldset->get('name');
        echo $this->formLabel($name);
        echo $this->formElementErrors($name, array('class' => 'formError'));
        echo $this->formInput($name);
        ?>
    </div>
    <div class="element">
        <?php
        $description = $fieldset->get('description');
        echo $this->formLabel($description);
        echo $this->formElementErrors($description, array('class' => 'formError'));
        echo $this->formTextarea($description);
        ?>
    </div>
    <div class="element">
        <?php
        $parentCategory = $fieldset->get('parentCategory');
        echo $this->formLabel($parentCategory);
        echo $this->formElementErrors($parentCategory, array('class' => 'formError'));
        echo $this->formSelect($parentCategory);
        ?>
    </div>
    <div class="element">
        <?php
        $thumbnail = $fieldset->get('thumbnail');
        echo $this->formLabel($thumbnail);
        echo $this->formElementErrors($thumbnail, array('class' => 'formError'));
        echo $this->formFile($thumbnail);
        ?>
    </div>
    <div class="element">
        <?php
        $position = $fieldset->get('position');
        echo $this->formLabel($position);
        echo $this->formElementErrors($position, array('class' => 'formError'));
        echo $this->formInput($position);
        ?>
    </div>
    <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
    <?php echo $this->form()->closeTag() ?>
</div>