<div class="tableWrapper" data-entity="categories">
    <?php echo $this->partial("table_options", array(
        "paginator" => $this->paginator,
        "location" => "categories"
    )); ?>
    <div class="tableHeader">
        <div class="tableColumn">
            <span>Id</span>
            <span class="sortable"><?php echo $this->translate("Name"); ?></span>
            <span><?php echo $this->translate("Description"); ?></span>
            <span><?php echo $this->translate("Parent Category"); ?></span>
            <span><?php echo $this->translate("Thumbnail"); ?></span>
            <span class="sortable"><?php echo $this->translate("Position"); ?></span>
        </div>
    </div><!--
    --><div class="tableBody">
        <?php
        foreach ($this->paginator as $category)
            echo $this->partial('category', array(
                "category" => $category,
                "categoriesSelect" => $categoriesSelect
            ));
        ?>
    </div>
</div>