<div id="optionPanel">
    <span class="addPartnerToggle">+ <?php echo $this->translate("Add Partner"); ?></span>
    <span id="saveChanges"><?php echo $this->translate("Save"); ?></span>
</div>
<div id="addPartner" class="formWrapper">
    <?php
    $form->prepare();
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('partner');
    $form->setAttribute('action', $this->url('partners/add'));
    echo $this->form()->openTag($form);
//    echo $this->formHidden($form->get('security'));
    ?>
    <table>
        <thead>
        <tr>
            <th><?php echo $this->translate("Name"); ?></th>
            <th><?php echo $this->translate("Website"); ?></th>
            <th><?php echo $this->translate("Description"); ?></th>
            <th><?php echo $this->translate("Thumbnail"); ?>*</th>
            <th><?php echo $this->translate("Add"); ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php
                echo $this->formInput($fieldset->get('name'));
                echo $this->formElementErrors($fieldset->get('name'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('website'));
                echo $this->formElementErrors($fieldset->get('website'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formTextarea($fieldset->get('description'));
                echo $this->formElementErrors($fieldset->get('description'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formFile($fieldset->get('thumbnail'));
                echo $this->formElementErrors($fieldset->get('thumbnail'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php echo $this->form()->closeTag() ?>
</div>
<div class="tableWrapper">
    <table id="partners" class="editableTable target-partner">
        <?php
        for ($i = 0; $i < 5; $i++)
            echo '<colgroup></colgroup>';
        ?>
        <thead>
        <tr>
            <th>Id</th>
            <th><?php echo $this->translate("Name"); ?></th>
            <th><?php echo $this->translate("Website"); ?></th>
            <th><?php echo $this->translate("Description"); ?></th>
            <th><?php echo $this->translate("Thumbnail"); ?></th>
            <th><?php echo $this->translate("Delete"); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        /**
         * @var \Application\Entity\Partner $partner
         */
        foreach ($this->partners as $partner):
            $description = $partner->getDescription();
            $thumbnail = $partner->getThumbnail();
            ?>
            <tr>
                <td class="partnerPartnerId"><?php echo $partner->getPartnerId(); ?></td>
                <td class="partnerName editText"><?php echo $partner->getName(); ?></td>
                <td class="partnerWebsite editText"><?php echo $partner->getWebsite(); ?></td>
                <td class="partnerDescription editTextfield"><textarea class="invisible"><?php echo $description ? $description : " - "; ?></textarea></td>
                <td class="partnerThumbnail editImage required">
                    <span class="fileMeta invisible">images/partners/<?php echo uniqid("partner_").rand(1000000,9999999); ?>.jpg</span>
                    <span class="fileImage"><?php echo $thumbnail ? '<img src="' . $this->basePath('images/partners/' . $thumbnail) . '" alt="' . $this->translate("partner image") . '" />' : ' - '; ?></span>
                </td>
                <td class="delete unEditable">X</td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div id="editPanel">
    <textarea class="editInput"></textarea>
    <span id="editDone"><?php echo $this->translate("Done"); ?></span>
</div>