<div class="formWrapper">
    <h2>Add a new Slide</h2>
    <?php
    $form->prepare();
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('slide');
    $form->setAttribute('action', $this->url('slides/add'));
    echo $this->form()->openTag($form);
    ?>
    <div class="element">
        <?php
        $url = $fieldset->get('url');
        echo $this->formLabel($url);
        echo $this->formElementErrors($url, array('class' => 'formError'));
        echo $this->formInput($url);
        ?>
    </div>
    <div class="element">
        <?php
        $position = $fieldset->get('position');
        echo $this->formLabel($position);
        echo $this->formElementErrors($position, array('class' => 'formError'));
        echo $this->formInput($position);
        ?>
    </div>
    <div class="element">
        <?php
        $caption = $fieldset->get('caption');
        echo $this->formLabel($caption);
        echo $this->formElementErrors($caption, array('class' => 'formError'));
        echo $this->formInput($caption);
        ?>
    </div>
    <div class="element">
        <?php
        $thumbnail = $fieldset->get('thumbnail');
        echo $this->formLabel($thumbnail);
        echo $this->formElementErrors($thumbnail, array('class' => 'formError'));
        echo $this->formFile($thumbnail);
        ?>
    </div>
    <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
    <?php echo $this->form()->closeTag() ?>
</div>