<div class="tableWrapper" data-entity="slides">
    <?php echo $this->partial("table_options", array(
        "paginator" => $this->paginator,
        "location" => "slides"
    )); ?>
    <div class="tableHeader">
        <div class="tableColumn">
            <span>Id</span>
            <span class="sortable"><?php echo $this->translate("Url"); ?></span>
            <span class="sortable"><?php echo $this->translate("Position"); ?></span>
            <span><?php echo $this->translate("Caption"); ?></span>
            <span><?php echo $this->translate("Thumbnail"); ?></span>
        </div>
    </div>
    <div class="tableBody">
        <?php
        foreach ($this->paginator as $slide)
            echo $this->partial('slide', array(
                "slide" => $slide,
            ));
        ?>
    </div>
</div>