<?php
/**
 * @var \Zend\Form\Fieldset $fieldset
 */
$fieldset = $form->get('user');
$form->prepare();
$form->setAttribute('action', $this->url('users/add'));
echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('security'));
?>
<table>
    <thead>
    <tr>
        <th><?php echo $this->translate("Username"); ?>*</th>
        <th><?php echo $this->translate("Password"); ?>*</th>
        <th><?php echo $this->translate("Email"); ?></th>
        <th><?php echo $this->translate("Add"); ?></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <?php
            echo $this->formInput($fieldset->get('username'));
            echo $this->formElementErrors($fieldset->get('username'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('password'));
            echo $this->formElementErrors($fieldset->get('password'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formEmail($fieldset->get('email'));
            echo $this->formElementErrors($fieldset->get('email'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
        </td>
    </tr>
    </tbody>
</table>
<?php echo $this->form()->closeTag() ?>