<div id="main">
    <div class="module">
        <?php echo $content->getContent(); ?>
    </div>
</div>
<div id="sidebar">
    <?php
    foreach ($partners as $partner):
        $name = $partner->getName();
        $website = $partner->getWebsite();
        ?>
        <li class="partner">
            <div class="title"><?php echo $name; ?></div>
            <img class="thumbnail" src="<?php echo $this->basePath('images/partners/' . $partner->getThumbnail()); ?>"
                 alt="partner image"/>
            <a href="http://<?php echo $website; ?>" target="_blank" title="<?php echo $name; ?>'s Website"><?php echo $website; ?></a>
            <div class="moduleBody">
                <?php echo $partner->getDescription(); ?>
            </div>
        </li>
    <?php endforeach; ?>
</div>